name: Deploy Prod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: UnlyEd/github-action-deploy-on-vercel@latest
        with:
          command: "vercel --confirm --prod --token ${{ secrets.VERCEL_TOKEN }}"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
